### ISSUE TITLE
RuntimeError: Invalid DISPLAY variable

### ISSUE THREAD

**Issue by cmagness** [mfixstsci/peewee4cosmo#1]
monitors side of things crashes when trying to produce plots

full traceback:

Traceback (most recent call last):
  File "/user/cmagness/miniconda3_linux/envs/monitors/bin/cm_monitors", line 11, in <module>
    load_entry_point('cosmo-peewee==0.0.1', 'console_scripts', 'cm_monitors')()
  File "/user/cmagness/miniconda3_linux/envs/monitors/lib/python2.7/site-packages/cosmo_peewee-0.0.1-py2.7.egg/cosmo_peewee/database/ingest.py", line 764, in run_monitors
    osm_monitor()
  File "/user/cmagness/miniconda3_linux/envs/monitors/lib/python2.7/site-packages/cosmo_peewee-0.0.1-py2.7.egg/cosmo_peewee/osm/monitor.py", line 1746, in monitor
    make_plots(flash_data, rawacq_data, monitor_dir)
  File "/user/cmagness/miniconda3_linux/envs/monitors/lib/python2.7/site-packages/cosmo_peewee-0.0.1-py2.7.egg/cosmo_peewee/osm/monitor.py", line 783, in make_plots
    fig = plt.figure(figsize=(16,8))
  File "/user/cmagness/miniconda3_linux/envs/monitors/lib/python2.7/site-packages/matplotlib/pyplot.py", line 548, in figure
    **kwargs)
  File "/user/cmagness/miniconda3_linux/envs/monitors/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/user/cmagness/miniconda3_linux/envs/monitors/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 167, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure)
  File "/user/cmagness/miniconda3_linux/envs/monitors/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 24, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/user/cmagness/miniconda3_linux/envs/monitors/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 234, in __init__
    _create_qApp()
  File "/user/cmagness/miniconda3_linux/envs/monitors/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 125, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable

**Comment by cmagness** [comment]
this was resolved by some changes mees made to the plotting algorithm

**Comment by cmagness** [comment]
this actually was not resolved by a different version of the code, but was resolved by running the code outside of a cron job. something about the servers is making this crash. needs further investigating.
